### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by ridings3d** [sibbell/sibbell-issues#40] opened 2015-12-23 21:59 UTC
I have tried to register for Sibbell but when I try I keep getting a 500 server error.

Thank you,
Ryan

**Comment by davegaeddert** [comment] 2015-12-25 03:26
Hey @ridings3d, I'm not sure what happened here yet, but I cleaned up some things regarding your account. Would you mind trying to sign up again?

**Comment by bripkens** [comment] 2015-12-26 09:59
I just ran into the same error.

**Comment by ahmedtds** [comment] 2015-12-27 13:08
i get same error when trying to sign up.

**Comment by jfradj** [comment] 2015-12-27 14:07
Same here.
I've just ping them on twitter ;-)

**Comment by ridings3d** [comment] 2015-12-27 20:10
I just tried it again and still a 500 server error.

**Comment by davegaeddert** [comment] 2015-12-28 22:48
Hey everybody -- I'm having a hard time tracking this down but I've restarted some services and have seen some signups come through since. Could someone give it a try and let me know if things are working again?

**Comment by bripkens** [comment] 2015-12-28 22:57
@davegaeddert: I retried with the same result :(

**Comment by bripkens** [comment] 2015-12-28 23:37
An email address verification email just hit my inbox. Upon click on the verification link, I got the same error.

<img width="318" alt="screen shot 2015-12-29 at 00 35 53" src="https://cloud.githubusercontent.com/assets/596443/12027274/3dea94d0-adc4-11e5-88e5-d3e8e5203a77.png">

**Comment by davegaeddert** [comment] 2015-12-29 00:05
@bripkens can you try one more time? Sorry!

**Comment by bripkens** [comment] 2015-12-29 00:13
@davegaeddert: Thanks, it worked! I didn't have to reauthenticate or anything. Visiting the website was sufficient.

Thank you for your effort!

**Comment by davegaeddert** [comment] 2015-12-29 02:20
Great. I'll close this for now. If anybody else still has issues, just let me know.

**Closed by davegaeddert** 2015-12-29 02:20 UTC

**Comment by ridings3d** [comment] 2015-12-29 04:26
I am still having issues. I really don't know what is going on. I got the authorize email but still nothing. When I visit sibbell.com now it automatically redirects me to sibbell.com/start and that is where the 500 server comes up.

**Comment by jfradj** [comment] 2015-12-29 07:13
Working for me guys.
Thx for your efforts.
Cheers

**Comment by davegaeddert** [comment] 2015-12-30 20:51
Sorry to hear it @ridings3d. I'm really not sure what the deal is. I went ahead and deleted everything related to your account. Would you mind trying one more time?!

**Comment by ridings3d** [comment] 2016-01-07 20:02
HEY IT WORKS!!!! Mark this bad boy closed. Thank you!

**Comment by XhmikosR** [comment] 2016-01-26 07:19
@davegaeddert: I'm too facing error 500 after authorizing Sibell. :/

**Comment by markyleong** [comment] 2016-01-28 06:38
@davegaeddert I'm having a similar problem:

1. Click login on https://sibbell.com/about/
2. Authorize application on https://github.com/login/oauth/authorize/...
3. Server Error 500 on https://sibbell.com/complete/github/?code=....

Sibbell then appears on https://github.com/settings/applications, but if I navigate to https://sibbell.com/about/ it shows that I'm not logged in yet.

I've tried revoking the Sibbell access on https://github.com/settings/applications and repeating the login but the same thing happens each time.

**Comment by ctmay4** [comment] 2016-02-10 21:54
Same exact issue has @markyleong 

Tried both yesterday and today and still the 500 error.  Any updates?

**Comment by davegaeddert** [comment] 2016-02-14 02:07
@XhmikosR @markyleong @ctmay4 sorry for not getting to this sooner. Feel free to give it another try if you're still interested, let me know if you still have trouble.

**Comment by XhmikosR** [comment] 2016-02-14 07:57
@davegaeddert: confirmed, now it works. Thanks!

**Comment by markyleong** [comment] 2016-02-14 07:59
@davegaeddert works for me too, thanks!

**Comment by ctmay4** [comment] 2016-02-15 03:40
Still a 500 error for me.

**Comment by PeteCrighton** [comment] 2016-02-18 21:46
@davegaeddert 500 error here as well.

**Comment by itsjustmath** [comment] 2016-02-21 08:26
also getting a 500 error :disappointed:

**Comment by nuno-agostinho** [comment] 2016-02-24 22:03
Also having this error.

**Comment by davegaeddert** [comment] 2016-03-01 22:58
@ctmay4 @PeteCrighton @itsjustmath @nuno-agostinho I cleaned up your accounts -- feel free to give it another try

**Comment by PeteCrighton** [comment] 2016-03-01 23:06
Thanks, it works now.

**Comment by itsjustmath** [comment] 2016-03-01 23:07
works for me! :+1:  thanks!

**Comment by ctmay4** [comment] 2016-03-02 14:04
Works now.  Thanks.

**Comment by nuno-agostinho** [comment] 2016-03-02 17:55
Working for me now, thanks. How come you don't "clean" (I don't understand what you mean by this) all new accounts automatically?

**Comment by BGraco** [comment] 2016-03-17 10:16
I am getting a 500 error as well.

**Comment by aprilhalasz** [comment] 2016-03-30 22:01
I'm seeing this same 500 error :/ can you "clean" my account?

**Comment by Abildtoft** [comment] 2016-04-03 21:06
I'm unfortunately also getting the 500 error

**Comment by labithiotis** [comment] 2016-04-04 19:09
Getting same error too, tried revoking github access but same result. Any other solutions?

**Comment by markhobden** [comment] 2016-04-07 13:01
Hi, would it also be possible to "clean" my account?   Thanks.

**Comment by BGraco** [comment] 2016-04-07 13:03
I am out of the office until 04/11/2016.

Urgent Items can be directed to Mark Brudevold.


Note: This is an automated response to your message  "Re:
[sibbell/sibbell-issues] 500 Server Error (#40)" sent on 04/07/2016 8:01:31
.

This is the only notification you will receive while this person is away.

**Comment by davegaeddert** [comment] 2016-04-11 19:54
Locking this in favor of #44 -- I wrote a quick explanation there of what's going on with Sibbell in general. Thanks for understanding! Make a comment there if you're still having trouble signing in.
